# Generated by Django 5.0.7 on 2025-02-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
